Repository WildCodeSchool/lyon-js-sept21-p2-g1-back, pull requests merged in 2021-11, with the labels that each got.

#1 first commit, init the project
  .env.sample
  .gitignore
  app.js
  db-config.js
  package-lock.json
  package.json
Labels: WIP

#3 Place free api
  .env.sample
  app.js
  db.js
  package-lock.json
  package.json
  placesFree.jsx
  reset-db.sql
Labels: WIP, Ready for prod

#4 Api rating db
  .env-sample
  app.js
  db.js
  package-lock.json
  reset-db.sql
Labels: Ready for prod
